Repository openstack-k8s-operators/osp-director-operator, pull requests merged in 2021-11, with the labels that each got.

#430 Bump ctrl-gen version for OpSDK 1.13.1
  Makefile
  api/v1beta1/openstackbaremetalset_webhook.go
  api/v1beta1/openstackcontrolplane_webhook.go
  api/v1beta1/openstackephemeralheat_webhook.go
  api/v1beta1/openstacknet_webhook.go
  api/v1beta1/openstackprovisionserver_webhook.go
  api/v1beta1/openstackvmset_webhook.go
  config/crd/bases/osp-director.openstack.org_openstackbaremetalsets.yaml
  config/crd/bases/osp-director.openstack.org_openstackclients.yaml
  config/crd/bases/osp-director.openstack.org_openstackconfigversions.yaml
  config/crd/bases/osp-director.openstack.org_openstackcontrolplanes.yaml
  config/crd/bases/osp-director.openstack.org_openstackephemeralheats.yaml
  config/crd/bases/osp-director.openstack.org_openstackipsets.yaml
  config/crd/bases/osp-director.openstack.org_openstackmacaddresses.yaml
  config/crd/bases/osp-director.openstack.org_openstacknets.yaml
  config/crd/bases/osp-director.openstack.org_openstackplaybookgenerators.yaml
  config/crd/bases/osp-director.openstack.org_openstackprovisionservers.yaml
  config/crd/bases/osp-director.openstack.org_openstackvmsets.yaml
  config/default/webhookcainjection_patch.yaml
  config/webhook/manifests.yaml
Labels: approved, lgtm

#431 Use ENV variables to set Image URL defaults
  api/v1beta1/openstackephemeralheat_webhook.go
  api/v1beta1/openstackprovisionserver_types.go
  api/v1beta1/openstackprovisionserver_webhook.go
  config/crd/bases/osp-director.openstack.org_openstackprovisionservers.yaml
  config/default/manager_auth_proxy_patch.yaml
Labels: approved, lgtm

#432 Revert "Use ENV variables to set Image URL defaults"
  api/v1beta1/openstackephemeralheat_webhook.go
  api/v1beta1/openstackprovisionserver_types.go
  api/v1beta1/openstackprovisionserver_webhook.go
  config/crd/bases/osp-director.openstack.org_openstackprovisionservers.yaml
  config/default/manager_auth_proxy_patch.yaml
Labels: approved, lgtm

#433 Use ENV variables to set Image URL defaults
  api/v1beta1/openstackephemeralheat_webhook.go
  api/v1beta1/openstackprovisionserver_types.go
  api/v1beta1/openstackprovisionserver_webhook.go
  api/v1beta1/zz_generated.deepcopy.go
  config/crd/bases/osp-director.openstack.org_openstackprovisionservers.yaml
  config/default/kustomization.yaml
  config/default/manager_default_images.yaml
  main.go
Labels: approved, lgtm

#434 Add relatedImages to base CSV
  config/manifests/bases/osp-director-operator.clusterserviceversion.yaml
Labels: approved, lgtm

#436 Follow-up for env vars for images
  api/v1beta1/openstackprovisionserver_webhook.go
  config/webhook/manifests.yaml
Labels: approved, lgtm

#439 Use lowercase role names to get VMs for fence CM generation
  controllers/openstackplaybookgenerator_controller.go
Labels: approved, lgtm

#438 Convert CSV to image digests during build...
  config/manifests/bases/osp-director-operator.clusterserviceversion.yaml
  scripts/build_and_push_images.sh
Labels: approved

#397 Add script to help stage downstream rebases
  scripts/stage_downstream_rebase.sh
Labels: approved

#440 Add changelog for 1.1.0 release
  changelog.txt
Labels: approved

#443 Add OpenStackClientImageURL to relatedImages, etc
  PROJECT
  api/v1beta1/openstackcontrolplane_types.go
  api/v1beta1/openstackcontrolplane_webhook.go
  api/v1beta1/openstackplaybookgenerator_types.go
  api/v1beta1/openstackplaybookgenerator_webhook.go
  api/v1beta1/zz_generated.deepcopy.go
  config/crd/bases/osp-director.openstack.org_openstackcontrolplanes.yaml
  config/crd/bases/osp-director.openstack.org_openstackplaybookgenerators.yaml
  config/default/manager_default_images.yaml
  config/manifests/bases/osp-director-operator.clusterserviceversion.yaml
  config/webhook/manifests.yaml
  main.go
Labels: approved, lgtm

#441 build script fixes: podman login check
  scripts/build_and_push_images.sh
Labels: approved, lgtm

#445 Use github action to build osp-director-operator images
  .github/create_bundle.sh
  .github/workflows/build-osp-director-operator.yaml
Labels: approved, lgtm

#437 Configure IPA client on openstackclient pod
  api/v1beta1/openstackclient_types.go
  api/v1beta1/openstackcontrolplane_types.go
  config/crd/bases/osp-director.openstack.org_openstackclients.yaml
  config/crd/bases/osp-director.openstack.org_openstackcontrolplanes.yaml
  controllers/openstackclient_controller.go
  controllers/openstackcontrolplane_controller.go
  pkg/openstackclient/const.go
  pkg/openstackclient/volumes.go
  templates/openstackclient/bin/init.sh
  templates/openstackclient/bin/kolla_config.json
  templates/openstackclient/bin/kolla_config_init.json
Labels: lgtm

#453 Use downstream default images for prov/downloader
  config/default/manager_default_images.yaml
  config/manifests/bases/osp-director-operator.clusterserviceversion.yaml
Labels: approved, lgtm

#444 build script fixes: podman login check
  scripts/build_and_push_images.sh
Labels: approved, lgtm
