Repository openstack-k8s-operators/osp-director-operator, pull requests merged in 2021-05, with the labels that each got.

#217 Use biosdev nic naming for overcloud nodes
  README.md
  api/v1beta1/openstackcontrolplane_types.go
  api/v1beta1/openstackvmset_types.go
  config/crd/bases/osp-director.openstack.org_openstackcontrolplanes.yaml
  config/crd/bases/osp-director.openstack.org_openstackvmsets.yaml
  config/samples/osp-director_v1beta1_openstackcontrolplane.yaml
  config/samples/osp-director_v1beta1_openstackcontrolplane_with_additional_custom_role.yaml
  config/samples/osp-director_v1beta1_openstackvmset.yaml
  controllers/openstackcontrolplane_controller.go
  controllers/openstackvmset_controller.go
  templates/vmset/cloudinit/networkdata
Labels: approved, lgtm

#212 Playbook generator
  .gitignore
  PROJECT
  README.md
  api/v1beta1/openstackephemeralheat_types.go
  api/v1beta1/openstackephemeralheat_webhook.go
  api/v1beta1/openstackplaybookgenerator_types.go
  api/v1beta1/zz_generated.deepcopy.go
  bundle.Dockerfile
  config/crd/bases/osp-director.openstack.org_openstackephemeralheats.yaml
  config/crd/bases/osp-director.openstack.org_openstackplaybookgenerators.yaml
  config/crd/kustomization.yaml
  config/crd/patches/cainjection_in_openstackephemeralheats.yaml
  config/crd/patches/cainjection_in_openstackplaybookgenerators.yaml
  config/crd/patches/webhook_in_openstackephemeralheats.yaml
  config/crd/patches/webhook_in_openstackplaybookgenerators.yaml
  config/manifests/bases/osp-director-operator.clusterserviceversion.yaml
  config/rbac/openstackephemeralheat_editor_role.yaml
  config/rbac/openstackephemeralheat_viewer_role.yaml
  config/rbac/openstackplaybookgenerator_editor_role.yaml
  config/rbac/openstackplaybookgenerator_viewer_role.yaml
  config/rbac/role.yaml
  config/rbac/service_account.yaml
  config/samples/osp-director_v1beta1_openstackephemeralheat.yaml
  config/samples/osp-director_v1beta1_openstackplaybookgenerator.yaml
  config/webhook/manifests.yaml
  controllers/openstackclient_controller.go
  controllers/openstackephemeralheat_controller.go
  controllers/openstackplaybookgenerator_controller.go
  controllers/suite_test.go
  go.sum
  main.go
  pkg/common/job_util.go
  pkg/openstackclient/volumes.go
  pkg/openstackephemeralheat/const.go
  pkg/openstackephemeralheat/heat.go
  pkg/openstackephemeralheat/mariadb.go
  pkg/openstackephemeralheat/rabbitmq.go
  pkg/openstackplaybookgenerator/const.go
  pkg/openstackplaybookgenerator/job.go
  pkg/openstackplaybookgenerator/volumes.go
  templates/openstackclient/bin/tripleo-deploy.sh
  templates/openstackephemeralheat/bin/galera.cnf
  templates/openstackephemeralheat/bin/heat.conf
  templates/openstackephemeralheat/bin/heat_config.json
  templates/openstackephemeralheat/bin/heat_engine_config.json
  templates/openstackephemeralheat/bin/heat_noauth.policy
  templates/openstackephemeralheat/bin/heat_paste.ini
  templates/openstackephemeralheat/bin/heat_token.json
  templates/openstackephemeralheat/bin/mariadb_config.json
  templates/openstackephemeralheat/bin/mariadb_init.sh
  templates/openstackephemeralheat/bin/mariadb_init_config.json
  templates/openstackephemeralheat/bin/rabbitmq-env.conf
  templates/openstackephemeralheat/bin/rabbitmq.config
  templates/openstackephemeralheat/bin/rabbitmq_config.json
  templates/openstackplaybookgenerator/bin/create-playbooks.sh
Labels: approved

#224 fix interface names in readme
  README.md
Labels: approved, lgtm

#226 Kuttl tests compatible with AI and IPI
  config/samples/osp-director_v1beta1_openstacknet.yaml
  config/samples/osp-director_v1beta1_openstacknet_ctlplane.yaml
  config/samples/osp-director_v1beta1_openstacknet_external.yaml
  config/samples/osp-director_v1beta1_openstacknet_internalapi.yaml
  config/samples/osp-director_v1beta1_openstacknet_sriov.yaml
  config/samples/osp-director_v1beta1_openstacknet_storage.yaml
  config/samples/osp-director_v1beta1_openstacknet_storagemgmt.yaml
  config/samples/osp-director_v1beta1_openstacknet_tenant.yaml
  tests/kuttl/tests/openstackcontrolplane_scale/00-prep.yaml
  tests/kuttl/tests/openstackcontrolplane_scale/01-assert.yaml
  tests/kuttl/tests/openstackcontrolplane_scale/02-assert.yaml
  tests/kuttl/tests/openstackcontrolplane_scale/03-assert.yaml
  tests/kuttl/tests/openstackcontrolplane_scale/04-assert.yaml
  tests/kuttl/tests/openstackcontrolplane_scale/05-assert.yaml
  tests/kuttl/tests/openstackcontrolplane_scale/06-assert.yaml
Labels: approved, lgtm

#229 Ignore k8s_errors.IsNotFound on ephemeral heat cleanup
  controllers/openstackplaybookgenerator_controller.go
Labels: approved, lgtm

#228 README updates after OpenStackPlaybookGenerator integration
  README.md
  templates/openstackclient/bin/tripleo-deploy.sh
Labels: approved, lgtm

#227 Fixes a couple of items in the README
  README.md
Labels: approved, needs-ok-to-test

#234 rabbitmq: bump RABBITMQ_IO_THREAD_POOL_SIZE
  pkg/openstackephemeralheat/rabbitmq.go
Labels: approved, lgtm

#232 add note about using RWX for openStackClientStorageClass
  README.md
Labels: approved, lgtm, needs-ok-to-test

#231 BaremetalSet status improvements
  api/v1beta1/openstackbaremetalset_types.go
  api/v1beta1/zz_generated.deepcopy.go
  config/crd/bases/osp-director.openstack.org_openstackbaremetalsets.yaml
  controllers/openstackbaremetalset_controller.go
  go.mod
  go.sum
Labels: approved, lgtm

#238 Allow mysql to read its config
  templates/openstackephemeralheat/bin/galera.cnf
  templates/openstackephemeralheat/bin/mariadb_config.json
  templates/openstackephemeralheat/bin/mariadb_init_config.json
Labels: approved, lgtm

#240 Fix 'Property Container*Image not assigned' errors
  templates/openstackplaybookgenerator/bin/create-playbooks.sh
Labels: approved, lgtm

#242 s/replicas/count in OSBMS sample
  config/samples/osp-director_v1beta1_openstackbaremetalset.yaml
Labels: approved

#241 Add git support for playbookgenerator
  README.md
  api/v1beta1/openstackclient_types.go
  api/v1beta1/openstackcontrolplane_types.go
  api/v1beta1/openstackplaybookgenerator_types.go
  config/crd/bases/osp-director.openstack.org_openstackclients.yaml
  config/crd/bases/osp-director.openstack.org_openstackcontrolplanes.yaml
  config/crd/bases/osp-director.openstack.org_openstackplaybookgenerators.yaml
  config/manifests/bases/osp-director-operator.clusterserviceversion.yaml
  config/samples/kustomization.yaml
  config/samples/osp-director_v1beta1_openstackplaybookgenerator.yaml
  controllers/openstackclient_controller.go
  controllers/openstackcontrolplane_controller.go
  controllers/openstackplaybookgenerator_controller.go
  pkg/openstackclient/volumes.go
  pkg/openstackplaybookgenerator/job.go
  pkg/openstackplaybookgenerator/volumes.go
  templates/openstackclient/bin/init.sh
  templates/openstackclient/bin/tripleo-deploy.sh
  templates/openstackplaybookgenerator/bin/create-playbooks.sh
Labels: approved, lgtm

#237 VMSet provisioning status
  api/v1beta1/common_types.go
  api/v1beta1/openstackbaremetalset_types.go
  api/v1beta1/openstackvmset_types.go
  api/v1beta1/zz_generated.deepcopy.go
  config/crd/bases/osp-director.openstack.org_openstackbaremetalsets.yaml
  config/crd/bases/osp-director.openstack.org_openstackclients.yaml
  config/crd/bases/osp-director.openstack.org_openstackcontrolplanes.yaml
  config/crd/bases/osp-director.openstack.org_openstackvmsets.yaml
  controllers/openstackbaremetalset_controller.go
  controllers/openstackvmset_controller.go
  go.sum
  pkg/vmset/status.go
Labels: approved, lgtm

#245 Add intf selection option to prov server
  api/v1beta1/openstackprovisionserver_types.go
  config/crd/bases/osp-director.openstack.org_openstackprovisionservers.yaml
  controllers/openstackprovisionserver_controller.go
Labels: approved, lgtm

#248 Remove RolesFile parameter
  README.md
  api/v1beta1/openstackplaybookgenerator_types.go
  config/crd/bases/osp-director.openstack.org_openstackplaybookgenerators.yaml
  controllers/openstackplaybookgenerator_controller.go
  go.mod
  go.sum
  templates/openstackplaybookgenerator/bin/create-playbooks.sh
Labels: approved, lgtm

#249 Fixes to playbookgenerator controller reconcile
  controllers/openstackplaybookgenerator_controller.go
Labels: approved, lgtm

#250 Fix tarball-config in config/samples
  config/samples/osp-director_v1beta1_openstackplaybookgenerator.yaml
Labels: approved, lgtm

#251 Fixes for playbookgenerator script
  templates/openstackplaybookgenerator/bin/create-playbooks.sh
Labels: approved, lgtm

#253 Small Readme tweak
  README.md
Labels: approved
