Repository openstack-k8s-operators/osp-director-operator, pull requests merged in 2022-03, with the labels that each got.

#523 Bump master version to 1.3.0
  Dockerfile
  Dockerfile.agent
  containers/agent/version.go
  containers/image_downloader/Dockerfile
Labels: approved, lgtm

#511 OSP minor update support
  OWNERS
  PROJECT
  api/v1beta1/openstackclient_types.go
  api/v1beta1/openstackclient_webhook.go
  api/v1beta1/openstackconfiggenerator_types.go
  api/v1beta1/openstackcontrolplane_types.go
  api/v1beta1/openstackcontrolplane_webhook.go
  api/v1beta1/openstackdeploy_types.go
  api/v1beta1/zz_generated.deepcopy.go
  config/crd/bases/osp-director.openstack.org_openstackbackups.yaml
  config/crd/bases/osp-director.openstack.org_openstackclients.yaml
  config/crd/bases/osp-director.openstack.org_openstackdeploys.yaml
  config/webhook/manifests.yaml
  containers/agent/deploy.go
  controllers/openstackclient_controller.go
  controllers/openstackcontrolplane_controller.go
  controllers/openstackdeploy_controller.go
  main.go
  pkg/openstackdeploy/job.go
  templates/openstackclient/bin/tripleo-deploy.sh
Labels: approved, lgtm

#526 Fix deploy
  api/v1beta1/openstacknetconfig_webhook.go
  config/default/manager_default_images.yaml
Labels: approved, lgtm, ok-to-test

#525 Use oc apply in Makefile
  Makefile
Labels: approved, lgtm, ok-to-test

#527 Script to customize staged images for testing
  scripts/customize_staged_images.sh
Labels: approved, lgtm

#521 [OSPK8-322] Introduce ipset again to also support service VIPs
  PROJECT
  README.md
  api/v1beta1/openstackbaremetalset_types.go
  api/v1beta1/openstackcontrolplane_types.go
  api/v1beta1/openstackcontrolplane_webhook.go
  api/v1beta1/openstackipset_types.go
  api/v1beta1/openstacknet_types.go
  api/v1beta1/openstacknet_webhook.go
  api/v1beta1/openstacknetconfig_types.go
  api/v1beta1/zz_generated.deepcopy.go
  config/crd/bases/osp-director.openstack.org_openstackbackups.yaml
  config/crd/bases/osp-director.openstack.org_openstackcontrolplanes.yaml
  config/crd/bases/osp-director.openstack.org_openstackipsets.yaml
  config/crd/bases/osp-director.openstack.org_openstacknets.yaml
  config/crd/kustomization.yaml
  config/crd/patches/cainjection_in_openstackipsets.yaml
  config/crd/patches/webhook_in_openstackipsets.yaml
  config/manifests/bases/osp-director-operator.clusterserviceversion.yaml
  config/rbac/openstackipset_editor_role.yaml
  config/rbac/openstackipset_viewer_role.yaml
  config/rbac/role.yaml
  config/samples/kustomization.yaml
  config/samples/osp-director_v1beta1_openstackipset.yaml
  controllers/openstackbaremetalset_controller.go
  controllers/openstackclient_controller.go
  controllers/openstackcontrolplane_controller.go
  controllers/openstackipset_controller.go
  controllers/openstacknetconfig_controller.go
  controllers/openstackvmset_controller.go
  main.go
  pkg/common/funcs.go
  pkg/openstackconfiggenerator/configmap.go
  pkg/openstackipset/funcs.go
  templates/openstackconfiggenerator/config/17.0/rendered-tripleo-config.yaml
  tests/kuttl/common/scripts/prep.sh
  tests/kuttl/common/tests/create_openstackcontrolplane-assert.yaml
  tests/kuttl/common/tests/create_openstackcontrolplane_single_net-assert.yaml
  tests/kuttl/common/tests/scale_down_openstackcontrolplane_single_controller-assert.yaml
  tests/kuttl/common/tests/scale_up_openstackcontrolplane_3_controllers-assert.yaml
  tests/kuttl/tests/openstackbaremetalset_scale/03-assert.yaml
  tests/kuttl/tests/openstackbaremetalset_scale/04-assert.yaml
  tests/kuttl/tests/openstackbaremetalset_scale/06-assert.yaml
  tests/kuttl/tests/openstackbaremetalset_scale/09-assert.yaml
  tests/kuttl/tests/openstacknetconfig_immutable_bridge_name/02-assert.yaml
Labels: approved, lgtm

#529 [OSPK8-447] Fix multi subnet network identification and routes rendering/template
  README.md
  pkg/openstacknetconfig/funcs.go
  templates/openstackconfiggenerator/config/16.2/network_data.yaml
  templates/openstackconfiggenerator/config/16.2/nic/net-config-multi-nic.yaml
  templates/openstackconfiggenerator/config/17.0/network_data.yaml
Labels: approved, lgtm

#524 Don't use custom noauth policy
  pkg/openstackephemeralheat/heat.go
  templates/openstackephemeralheat/bin/heat.conf
  templates/openstackephemeralheat/bin/heat_config.json
  templates/openstackephemeralheat/bin/heat_engine_config.json
  templates/openstackephemeralheat/bin/heat_noauth.policy
Labels: approved, lgtm, ok-to-test

#531 Fix check for upstream/downstream version for AdditionalServiceVIPs
  api/v1beta1/openstackcontrolplane_webhook.go
Labels: approved, lgtm

#532 [OSPK8-448] fix osnetcfg 'DESIRED NETWORKS' status
  controllers/openstacknetconfig_controller.go
Labels: approved, lgtm

#528 Cleanups to scripts/customize_staged_images.sh
  scripts/customize_staged_images.sh
Labels: approved, lgtm

#533 Update webhook/manifests.yaml for removed webhook
  config/webhook/manifests.yaml
Labels: approved, lgtm

#530 Support interrupting a deploy job
  containers/agent/deploy.go
  pkg/openstackclient/volumes.go
  pkg/openstackdeploy/job.go
  templates/openstackclient/bin/tripleo-deploy-term.sh
  templates/openstackclient/bin/tripleo-deploy.sh
Labels: approved, lgtm

#535 [OSPK8-385] Return template rendering error instead of panic
  controllers/openstackconfiggenerator_controller.go
  controllers/openstacknet_controller.go
  pkg/common/configmap.go
  pkg/common/secret.go
  pkg/common/template_util.go
Labels: approved, lgtm

#538 Bump containerd to avoid CVE detection with earlier versions
  go.mod
  go.sum
Labels: approved, lgtm

#537 Add generator name to ConfigVersion
  api/v1beta1/openstackconfigversion_types.go
  config/crd/bases/osp-director.openstack.org_openstackconfigversions.yaml
  pkg/openstackconfigversion/git_util.go
Labels: approved, lgtm

#539 initial Readme updates for OSDeploy
  README.md
Labels: approved, lgtm

#541 Handle DeployIdentifier
  api/v1beta1/openstackdeploy_types.go
  api/v1beta1/zz_generated.deepcopy.go
  config/crd/bases/osp-director.openstack.org_openstackdeploys.yaml
  controllers/openstackdeploy_controller.go
  pkg/openstackdeploy/job.go
  templates/openstackclient/bin/tripleo-deploy.sh
  templates/openstackconfiggenerator/config/16.2/rendered-tripleo-config.yaml
  templates/openstackconfiggenerator/config/17.0/rendered-tripleo-config.yaml
Labels: approved, lgtm

#547 drop imageUrl from config/samples
  config/samples/osp-director_v1beta1_openstackclient.yaml
  config/samples/osp-director_v1beta1_openstackconfiggenerator.yaml
Labels: approved, lgtm

#544 Change from CreateOrUpdate to CreateOrPatch and introduce ctx parameters
  config/rbac/role.yaml
  controllers/openstackbackup_controller.go
  controllers/openstackbackuprequest_controller.go
  controllers/openstackbaremetalset_controller.go
  controllers/openstackclient_controller.go
  controllers/openstackconfiggenerator_controller.go
  controllers/openstackcontrolplane_controller.go
  controllers/openstackdeploy_controller.go
  controllers/openstackephemeralheat_controller.go
  controllers/openstackipset_controller.go
  controllers/openstackmacaddress_controller.go
  controllers/openstacknet_controller.go
  controllers/openstacknetattachment_controller.go
  controllers/openstacknetconfig_controller.go
  controllers/openstackprovisionserver_controller.go
  controllers/openstackvmset_controller.go
  pkg/common/baremetal.go
  pkg/common/configmap.go
  pkg/common/controlplane.go
  pkg/common/job_util.go
  pkg/common/network.go
  pkg/common/pod.go
  pkg/common/pvc.go
  pkg/common/replicaset.go
  pkg/common/secret.go
  pkg/common/service.go
  pkg/common/virtualmachine.go
  pkg/openstackbackup/funcs.go
  pkg/openstackconfiggenerator/configmap.go
  pkg/openstackconfigversion/git_util.go
  pkg/openstackipset/funcs.go
  pkg/openstacknet/funcs.go
  pkg/openstacknet/sriov.go
  pkg/openstacknetattachment/funcs.go
  pkg/openstacknetattachment/sriov.go
  pkg/openstacknetconfig/funcs.go
Labels: approved

#548 Add missing descriptions on CRDs
  api/v1beta1/openstackbackuprequest_types.go
  api/v1beta1/openstackconfigversion_types.go
  api/v1beta1/openstackdeploy_types.go
  api/v1beta1/openstackephemeralheat_types.go
  api/v1beta1/openstackipset_types.go
  api/v1beta1/openstackmacaddress_types.go
  api/v1beta1/openstacknetattachment_types.go
  api/v1beta1/openstacknetconfig_types.go
  api/v1beta1/openstackprovisionserver_types.go
  config/crd/bases/osp-director.openstack.org_openstackbackuprequests.yaml
  config/crd/bases/osp-director.openstack.org_openstackbackups.yaml
  config/crd/bases/osp-director.openstack.org_openstackconfigversions.yaml
  config/crd/bases/osp-director.openstack.org_openstackdeploys.yaml
  config/crd/bases/osp-director.openstack.org_openstackephemeralheats.yaml
  config/crd/bases/osp-director.openstack.org_openstackipsets.yaml
  config/crd/bases/osp-director.openstack.org_openstackmacaddresses.yaml
  config/crd/bases/osp-director.openstack.org_openstacknetattachments.yaml
  config/crd/bases/osp-director.openstack.org_openstacknetconfigs.yaml
  config/crd/bases/osp-director.openstack.org_openstackprovisionservers.yaml
Labels: approved

#506 Add Role param to ConfigGenerator
  api/v1beta1/openstackconfiggenerator_types.go
  api/v1beta1/zz_generated.deepcopy.go
  config/crd/bases/osp-director.openstack.org_openstackconfiggenerators.yaml
  controllers/openstackconfiggenerator_controller.go
  pkg/openstackconfiggenerator/configmap.go
Labels: approved, lgtm

#551 [OSPK8-457] Allow adding new osnetattach definitions
  api/v1beta1/openstacknetconfig_webhook.go
Labels: approved, lgtm

#552 [OSPK8-458] Do not wait in osnetcfg for nncp
  PROJECT
  api/v1beta1/common_openstackcontrolplane.go
  api/v1beta1/common_types.go
  api/v1beta1/openstackdeploy_types.go
  api/v1beta1/openstackdeploy_webhook.go
  config/crd/bases/osp-director.openstack.org_openstackdeploys.yaml
  config/rbac/role.yaml
  config/webhook/manifests.yaml
  controllers/openstackbaremetalset_controller.go
  controllers/openstackconfiggenerator_controller.go
  controllers/openstacknetattachment_controller.go
  controllers/openstacknetconfig_controller.go
  pkg/common/controlplane.go
  pkg/openstackconfiggenerator/configmap.go
Labels: approved, lgtm

#519 Harvest overcloud.json after deployment
  README.md
  api/v1beta1/openstackconfigversion_types.go
  config/crd/bases/osp-director.openstack.org_openstackconfigversions.yaml
  config/rbac/service_account.yaml
  containers/agent/deploy.go
  controllers/openstackdeploy_controller.go
  pkg/openstackdeploy/configmap.go
  pkg/openstackdeploy/const.go
  pkg/openstackdeploy/job.go
Labels: approved, lgtm

#549 Mark macaddresses, and ipset as internal
  README.md
  config/manifests/bases/osp-director-operator.clusterserviceversion.yaml
Labels: approved, lgtm

#555 some fixes after 1.14 upgrade
  api/v1beta1/openstackbaremetalset_webhook.go
  api/v1beta1/openstackclient_webhook.go
  api/v1beta1/openstackdeploy_webhook.go
  api/v1beta1/openstackipset_webhook.go
  api/v1beta1/openstackvmset_webhook.go
  conf/osp-director.openstack.org_openstackbackuprequests.yaml
  conf/osp-director.openstack.org_openstackbackups.yaml
  conf/osp-director.openstack.org_openstackbaremetalsets.yaml
  conf/osp-director.openstack.org_openstackclients.yaml
  conf/osp-director.openstack.org_openstackconfiggenerators.yaml
  conf/osp-director.openstack.org_openstackconfigversions.yaml
  conf/osp-director.openstack.org_openstackcontrolplanes.yaml
  conf/osp-director.openstack.org_openstackdeploys.yaml
  conf/osp-director.openstack.org_openstackephemeralheats.yaml
  conf/osp-director.openstack.org_openstackipsets.yaml
  conf/osp-director.openstack.org_openstackmacaddresses.yaml
  conf/osp-director.openstack.org_openstacknetattachments.yaml
  conf/osp-director.openstack.org_openstacknetconfigs.yaml
  conf/osp-director.openstack.org_openstacknets.yaml
  conf/osp-director.openstack.org_openstackprovisionservers.yaml
  conf/osp-director.openstack.org_openstackvmsets.yaml
  config/manager/controller_manager_config.yaml
  config/webhook/manifests.yaml
Labels: approved, lgtm
